1821:0Traceback (most recent call last):
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/buildbot-0.8.7p1-py2.7.egg/buildbot/process/buildstep.py", line 541, in startStep
    d.addCallback(self._startStep_2)
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 301, in addCallback
    callbackKeywords=kw)
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 290, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/buildbot-0.8.7p1-py2.7.egg/buildbot/process/buildstep.py", line 587, in _startStep_2
    d = self.build.render(getattr(self, renderable))
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/buildbot-0.8.7p1-py2.7.egg/buildbot/process/properties.py", line 191, in render
    return props.render(value)
  File "/home/pidge/workspace/yocto-autobuilder/lib/python2.7/site-packages/buildbot-0.8.7p1-py2.7.egg/buildbot/process/properties.py", line 150, in render
    renderable = IRenderable(value)
exceptions.TypeError: ('Could not adapt', <buildbot.process.factory.BuildFactory instance at 0x3a66098>, <InterfaceClass buildbot.interfaces.IRenderable>)
,